config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :ads
  get 'home/about'

  root 'ads#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :ads
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /ads or /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1 or /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    # @ad = Ad.new
    @ad = current_user.ads.build
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    # @ad = Ad.new(ad_params)
    @ad = current_user.ads.build(ad_params )

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ad = current_user.ads.find_by(id: params[:id])
    redirect_to ads_path, notice: "Not authorized to edit" if @ad.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:title, :description, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/ads/_form.html.erb
<%= form_with(model: ad) do |form| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>


    <%= form.number_field :user_id, id: :ad_user_id, value:current_user.id, type: :hidden %>



  <div class="actions">
    <%= form.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<div class="row">
  <div class="col">
    <h1>View Ads</h1>
  </div>
</div>

<div class="row mb-5">
  <div class="col">
    <%= link_to 'New Ad', new_ad_path,  class: "btn btn-primary" %>
  </div>
</div>



<div class="row">
  <% @ads.each do |ad| %>
    <div class="col-12 col-lg-4">
      <div class="card shadow-sm p-3 mb-5 bg-white rounded">
        <div class="card-body">
          <h3 class="card-title">
            <%= link_to ad.title, ad %>
          </h3>
          <h6 class="card-subtitle mb-2 text-muted">Posted By: <%= ad.user.email %> </h6>
          <p class="card-text"><%= ad.description %></p>
          <% if ad.user == current_user %>
            <%= link_to 'Edit', edit_ad_path(ad), class: "btn btn-primary"%>
            <%=  link_to 'Delete', ad, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %>
          <%end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/ads/new.html.erb
<h1 class="mb-3">New Ad</h1>

<%= render 'form', ad: @ad %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>


<% if @ad.user == current_user %>
  <%= link_to 'Edit', edit_ad_path(@ad) %> |
  <%= link_to 'Back', ads_path %>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <%= link_to 'Adlister App', root_path, class:"navbar-brand"  %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Ads", ads_path, class:"nav-link" %>
      </li>


      <% if user_signed_in?  %>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Create Ad", new_ad_path, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>


      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Hello World!</p>
<p>First rails app!</p>

app/views/layouts/_alerts.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Adlister</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>

  <body>

    <%= render 'home/header' %>

    <div class="container">
      <% if notice  %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  </body>
</html>